import type { PostcodeData, FilterProduct, SupplierData } from "./types";

export const MOCK_READINGS = [
  { name: "Lead", value: 0.003, unit: "mg/L", ukLimit: 0.01, whoGuideline: 0.01, status: "pass" as const },
  { name: "Nitrate", value: 28.0, unit: "mg/L", ukLimit: 50.0, whoGuideline: 50.0, status: "pass" as const },
  { name: "PFAS (total)", value: 0.08, unit: "µg/L", ukLimit: null, whoGuideline: 0.1, status: "warning" as const, isPfas: true },
  { name: "PFOS", value: 0.03, unit: "µg/L", ukLimit: null, whoGuideline: 0.1, status: "pass" as const, isPfas: true },
  { name: "Chlorine residual", value: 0.42, unit: "mg/L", ukLimit: 5.0, whoGuideline: 5.0, status: "pass" as const },
  { name: "Turbidity", value: 0.8, unit: "NTU", ukLimit: 4.0, whoGuideline: 4.0, status: "pass" as const },
  { name: "Coliform bacteria", value: 0, unit: "count/100ml", ukLimit: 0, whoGuideline: 0, status: "pass" as const },
  { name: "E. coli", value: 0, unit: "count/100ml", ukLimit: 0, whoGuideline: 0, status: "pass" as const },
  { name: "Iron", value: 0.045, unit: "mg/L", ukLimit: 0.2, whoGuideline: 0.3, status: "pass" as const },
  { name: "Copper", value: 0.12, unit: "mg/L", ukLimit: 2.0, whoGuideline: 2.0, status: "pass" as const },
  { name: "Arsenic", value: 0.002, unit: "µg/L", ukLimit: 0.01, whoGuideline: 0.01, status: "pass" as const },
  { name: "Hardness (CaCO3)", value: 280, unit: "mg/L", ukLimit: null, whoGuideline: null, status: "pass" as const },
];

export const MOCK_POSTCODE: PostcodeData = {
  district: "SW1A",
  areaName: "Westminster",
  city: "London",
  region: "Greater London",
  supplier: "Thames Water",
  supplierId: "thames-water",
  supplyZone: "London Central",
  safetyScore: 7.2,
  scoreGrade: "good",
  contaminantsTested: 12,
  contaminantsFlagged: 2,
  pfasDetected: true,
  pfasLevel: 0.08,
  pfasSource: "environmental",
  lastUpdated: "2026-03-28",
  lastSampleDate: "2026-03-14",
  readings: MOCK_READINGS,
  nearbyPostcodes: ["SW1B", "SW1E", "SW1H", "SW1P", "SW1V", "SW1W", "SW1X", "SW1Y", "W1", "WC2"],
  historicalScores: [
    { year: 2020, score: 5.8 },
    { year: 2021, score: 6.1 },
    { year: 2022, score: 6.5 },
    { year: 2023, score: 6.9 },
    { year: 2024, score: 7.0 },
    { year: 2025, score: 7.1 },
    { year: 2026, score: 7.2 },
  ],
};

export const MOCK_POSTCODES: Record<string, PostcodeData> = {
  SW1A: MOCK_POSTCODE,
  E1: {
    ...MOCK_POSTCODE,
    district: "E1",
    areaName: "Whitechapel",
    city: "London",
    safetyScore: 6.8,
    scoreGrade: "fair",
    contaminantsFlagged: 3,
    pfasLevel: 0.09,
    readings: MOCK_READINGS.map((r) =>
      r.name === "PFAS (total)" ? { ...r, value: 0.09 } : r.name === "Lead" ? { ...r, value: 0.007 } : r
    ),
    nearbyPostcodes: ["E2", "E3", "E14", "EC1", "EC2", "EC3"],
    historicalScores: [
      { year: 2020, score: 5.2 },
      { year: 2021, score: 5.5 },
      { year: 2022, score: 5.9 },
      { year: 2023, score: 6.2 },
      { year: 2024, score: 6.5 },
      { year: 2025, score: 6.7 },
      { year: 2026, score: 6.8 },
    ],
  },
  M1: {
    ...MOCK_POSTCODE,
    district: "M1",
    areaName: "Manchester City Centre",
    city: "Manchester",
    region: "North West",
    supplier: "United Utilities",
    supplierId: "united-utilities",
    supplyZone: "Manchester Central",
    safetyScore: 8.1,
    scoreGrade: "good",
    contaminantsFlagged: 0,
    pfasDetected: false,
    pfasLevel: null,
    pfasSource: null,
    nearbyPostcodes: ["M2", "M3", "M4", "M5", "M6", "M7", "M8"],
    historicalScores: [
      { year: 2020, score: 7.5 },
      { year: 2021, score: 7.6 },
      { year: 2022, score: 7.8 },
      { year: 2023, score: 7.9 },
      { year: 2024, score: 8.0 },
      { year: 2025, score: 8.0 },
      { year: 2026, score: 8.1 },
    ],
  },
  B1: {
    ...MOCK_POSTCODE,
    district: "B1",
    areaName: "Birmingham City Centre",
    city: "Birmingham",
    region: "West Midlands",
    supplier: "Severn Trent",
    supplierId: "severn-trent",
    supplyZone: "Birmingham Central",
    safetyScore: 6.4,
    scoreGrade: "fair",
    contaminantsFlagged: 3,
    pfasDetected: true,
    pfasLevel: 0.06,
    pfasSource: "environmental",
    nearbyPostcodes: ["B2", "B3", "B4", "B5", "B6", "B7", "B8", "B9"],
    historicalScores: [
      { year: 2020, score: 5.5 },
      { year: 2021, score: 5.8 },
      { year: 2022, score: 6.0 },
      { year: 2023, score: 6.1 },
      { year: 2024, score: 6.2 },
      { year: 2025, score: 6.3 },
      { year: 2026, score: 6.4 },
    ],
  },
  LS1: {
    ...MOCK_POSTCODE,
    district: "LS1",
    areaName: "Leeds City Centre",
    city: "Leeds",
    region: "Yorkshire",
    supplier: "Yorkshire Water",
    supplierId: "yorkshire-water",
    supplyZone: "Leeds Central",
    safetyScore: 7.8,
    scoreGrade: "good",
    contaminantsFlagged: 1,
    pfasDetected: false,
    pfasLevel: null,
    pfasSource: null,
    nearbyPostcodes: ["LS2", "LS3", "LS4", "LS5", "LS6", "LS7"],
    historicalScores: [
      { year: 2020, score: 6.8 },
      { year: 2021, score: 7.0 },
      { year: 2022, score: 7.2 },
      { year: 2023, score: 7.4 },
      { year: 2024, score: 7.5 },
      { year: 2025, score: 7.7 },
      { year: 2026, score: 7.8 },
    ],
  },
};

export const MOCK_FILTERS: FilterProduct[] = [
  {
    id: "brita-maxtra-pro",
    brand: "BRITA",
    model: "MAXTRA PRO All-in-1",
    category: "jug",
    removes: ["chlorine", "lead", "copper", "pfas"],
    certifications: ["TÜV SÜD"],
    priceGbp: 29.99,
    affiliateUrl: "#",
    imageUrl: "",
    rating: 4.5,
    badge: "budget",
  },
  {
    id: "zerowater-ready-pour",
    brand: "ZeroWater",
    model: "Ready-Pour 10-Cup",
    category: "jug",
    removes: ["pfas", "lead", "chlorine", "chromium", "mercury"],
    certifications: ["NSF 53", "NSF 401"],
    priceGbp: 39.99,
    affiliateUrl: "#",
    imageUrl: "",
    rating: 4.3,
    badge: "best-match",
  },
  {
    id: "osmio-zero",
    brand: "Osmio",
    model: "Zero Installation Reverse Osmosis",
    category: "countertop",
    removes: ["pfas", "lead", "nitrate", "chlorine", "arsenic", "fluoride", "bacteria"],
    certifications: ["NSF 58"],
    priceGbp: 349,
    affiliateUrl: "#",
    imageUrl: "",
    rating: 4.7,
    badge: "whole-house",
  },
];

export const MOCK_SUPPLIERS: SupplierData[] = [
  { id: "thames-water", name: "Thames Water", region: "London and Thames Valley", customersM: 15, complianceRate: 99.96, website: "https://www.thameswater.co.uk", postcodeAreas: ["SW1A", "SW1B", "E1", "W1", "EC1", "N1", "SE1", "NW1"] },
  { id: "severn-trent", name: "Severn Trent", region: "Midlands", customersM: 8, complianceRate: 99.95, website: "https://www.stwater.co.uk", postcodeAreas: ["B1", "B2", "CV1", "DE1", "NG1", "ST1"] },
  { id: "united-utilities", name: "United Utilities", region: "North West", customersM: 7, complianceRate: 99.97, website: "https://www.unitedutilities.com", postcodeAreas: ["M1", "M2", "L1", "PR1", "WA1", "BL1"] },
  { id: "yorkshire-water", name: "Yorkshire Water", region: "Yorkshire", customersM: 5, complianceRate: 99.94, website: "https://www.yorkshirewater.com", postcodeAreas: ["LS1", "BD1", "HU1", "S1", "HG1", "YO1"] },
  { id: "anglian-water", name: "Anglian Water", region: "East of England", customersM: 4.5, complianceRate: 99.93, website: "https://www.anglianwater.co.uk", postcodeAreas: ["CB1", "IP1", "NR1", "PE1"] },
];

export const MOST_CHECKED = ["SW1A", "E1", "M1", "B1", "LS1", "BS1", "EH1", "CF1", "NE1", "G1"];
