import type { FilterProduct, ProductCategory } from "./types";

/**
 * Canonical product catalogue — single source of truth for all filter products.
 * 22 products across 7 categories.
 */
export const PRODUCTS: FilterProduct[] = [
  // ─── JUGS ───────────────────────────────────────────────────────────
  {
    id: "brita-maxtra-pro",
    brand: "BRITA",
    model: "Marella XL + MAXTRA PRO",
    slug: "brita-marella-xl",
    category: "jug",
    removes: ["Chlorine", "Lead", "Copper", "Mercury", "Cadmium"],
    certifications: ["TUV SUD"],
    priceGbp: 25,
    priceTier: "budget",
    affiliateUrl: "https://www.amazon.co.uk/dp/B0BT1HTR9Q?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/brita-marella.png",
    rating: 4.5,
    badge: "budget",
    pros: [
      "Affordable running costs with widely available filters",
      "No installation — ready to use out of the box",
      "3.5L capacity suits families of up to four",
    ],
    cons: [
      "Does not remove PFAS, fluoride, or nitrates",
      "MAXTRA PRO filters need replacing every 4 weeks",
      "Jug takes up fridge space",
    ],
    bestFor: "Basic chlorine and taste improvement on a budget",
    filterLife: "4 weeks per cartridge",
    annualCost: 52,
  },
  {
    id: "zerowater-12cup",
    brand: "ZeroWater",
    model: "12-Cup Ready-Pour",
    slug: "zerowater-12-cup",
    category: "jug",
    removes: [
      "Lead",
      "Chromium",
      "Mercury",
      "PFAS (total)",
      "Fluoride",
      "Nitrate",
      "Arsenic",
      "Cadmium",
    ],
    certifications: ["NSF/ANSI 53", "NSF/ANSI 401"],
    priceGbp: 40,
    priceTier: "mid",
    affiliateUrl: "https://www.amazon.co.uk/dp/B07J2HJMKQ?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/zerowater-12cup.jpg",
    rating: 4.3,
    badge: "best-match",
    pros: [
      "NSF-certified to remove PFAS and heavy metals",
      "Includes TDS meter so you can verify performance",
      "5-stage filtration in a simple jug format",
    ],
    cons: [
      "Filters last only 2–3 weeks in hard water areas",
      "Slower pour rate than BRITA — takes 5+ minutes to fill",
      "Replacement filters cost more than competitors",
    ],
    bestFor: "Households concerned about PFAS and heavy metals",
    filterLife: "2–4 weeks depending on TDS",
    annualCost: 120,
  },
  {
    id: "aqua-optima-evolve",
    brand: "Aqua Optima",
    model: "Liscia + Evolve+",
    slug: "aqua-optima-liscia",
    category: "jug",
    removes: ["Chlorine", "Lead", "Copper", "Mercury"],
    certifications: ["TUV SUD"],
    priceGbp: 20,
    priceTier: "budget",
    affiliateUrl: "https://www.amazon.co.uk/dp/B09ZL1LN6V?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/aqua-optima.png",
    rating: 4.4,
    badge: "budget",
    pros: [
      "Cheapest jug option with BRITA-compatible filters",
      "Slim fridge-door design saves space",
      "Evolve+ filters last 30 days",
    ],
    cons: [
      "Fewer contaminants removed than ZeroWater",
      "2.4L filtered capacity — small for families",
      "Lid can leak if not seated properly",
    ],
    bestFor: "Budget-conscious buyers wanting basic filtration",
    filterLife: "30 days per cartridge",
    annualCost: 36,
  },
  {
    id: "pur-plus-pitcher",
    brand: "PUR",
    model: "Plus 11-Cup Pitcher",
    slug: "pur-plus-pitcher",
    category: "jug",
    removes: ["Chlorine", "Lead", "Mercury", "Cadmium", "Copper"],
    certifications: ["NSF/ANSI 42", "NSF/ANSI 53"],
    priceGbp: 35,
    priceTier: "mid",
    affiliateUrl: "https://www.amazon.co.uk/dp/B0B9J4N1ZH?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/pur-plus-pitcher.png",
    rating: 4.2,
    badge: "best-value",
    pros: [
      "NSF 53 certified for lead removal",
      "Large 11-cup capacity suits bigger households",
      "Filter-change indicator light on lid",
    ],
    cons: [
      "Does not remove PFAS or fluoride",
      "Harder to find replacement filters in UK shops",
      "Filtering a full jug takes 10+ minutes",
    ],
    bestFor: "Families wanting certified lead removal in a large jug",
    filterLife: "2 months per cartridge",
    annualCost: 60,
  },

  // ─── COUNTERTOP ─────────────────────────────────────────────────────
  {
    id: "waterdrop-fc06",
    brand: "Waterdrop",
    model: "WD-FC-06 Tap Filter",
    slug: "waterdrop-fc-06",
    category: "countertop",
    removes: ["Chlorine", "Lead", "Fluoride"],
    certifications: ["NSF/ANSI 42"],
    priceGbp: 30,
    priceTier: "budget",
    affiliateUrl: "https://www.amazon.co.uk/dp/B08JPCYHYQ?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/waterdrop-fc06.png",
    rating: 4.3,
    badge: "budget",
    pros: [
      "Clips onto most standard UK taps in minutes",
      "Switch between filtered and unfiltered flow",
      "Compact design that doesn't dominate the counter",
    ],
    cons: [
      "Not compatible with pull-out or spray taps",
      "Limited contaminant removal compared to under-sink",
      "Filter lasts only 3 months at average use",
    ],
    bestFor: "Quick chlorine and lead reduction without plumbing",
    filterLife: "3 months",
    annualCost: 48,
    flowRate: "2.0 L/min",
  },
  {
    id: "tapp-water-ecopro",
    brand: "TAPP Water",
    model: "EcoPro",
    slug: "tapp-water-ecopro",
    category: "countertop",
    removes: ["Chlorine", "Lead", "Microplastics", "PFAS (total)"],
    certifications: ["SGS tested"],
    priceGbp: 60,
    priceTier: "mid",
    affiliateUrl: "https://www.amazon.co.uk/dp/B0BXJL6MNK?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/tapp-ecopro.png",
    rating: 4.4,
    badge: "best-match",
    pros: [
      "Removes microplastics and PFAS — rare for a tap filter",
      "Biodegradable filter cartridges reduce waste",
      "Subscription model means filters arrive on time",
    ],
    cons: [
      "SGS tested rather than NSF certified",
      "Higher upfront cost than basic tap filters",
      "Requires specific tap adapter — check compatibility first",
    ],
    bestFor: "Eco-conscious households wanting PFAS removal at the tap",
    filterLife: "3 months",
    annualCost: 80,
    flowRate: "4.0 L/min",
  },

  // ─── UNDER-SINK (NON-RO) ───────────────────────────────────────────
  {
    id: "waterdrop-10ua",
    brand: "Waterdrop",
    model: "10UA Under Sink",
    slug: "waterdrop-10ua",
    category: "under_sink",
    removes: ["Chlorine", "Lead", "PFAS (total)"],
    certifications: ["NSF/ANSI 42"],
    priceGbp: 45,
    priceTier: "budget",
    affiliateUrl: "https://www.amazon.co.uk/dp/B083NPW1DN?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/waterdrop-10ua.png",
    rating: 4.4,
    badge: "budget",
    pros: [
      "Massive 11,000-gallon filter life — lasts most households a year",
      "Simple DIY installation with push-fit connectors",
      "Compact body fits easily under standard UK sinks",
    ],
    cons: [
      "Fewer contaminants removed than RO systems",
      "Needs a dedicated filtered-water tap or adapter",
      "Single-stage filtration won't catch everything",
    ],
    bestFor: "High-volume under-sink filtration without RO complexity",
    filterLife: "12 months",
    annualCost: 30,
    flowRate: "3.8 L/min",
  },
  {
    id: "doulton-hip-ultracarb",
    brand: "Doulton",
    model: "HIP Ultracarb",
    slug: "doulton-hip-ultracarb",
    category: "under_sink",
    removes: ["Chlorine", "Lead", "Bacteria", "Microplastics", "Copper"],
    certifications: ["NSF/ANSI 42", "NSF/ANSI 53"],
    priceGbp: 120,
    priceTier: "mid",
    affiliateUrl: "https://www.amazon.co.uk/dp/B005HSFMDI?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/doulton-hip-ultracarb.png",
    rating: 4.6,
    badge: "best-match",
    pros: [
      "Ceramic element removes 99.99% of bacteria",
      "British-made with over 190 years of heritage",
      "NSF 42 + 53 dual certification for lead and cysts",
    ],
    cons: [
      "Higher upfront cost than basic carbon filters",
      "Flow rate drops as ceramic element loads — needs periodic cleaning",
      "Does not remove PFAS or fluoride",
    ],
    bestFor: "Families wanting bacteria and lead removal from a trusted UK brand",
    filterLife: "6 months",
    annualCost: 80,
    flowRate: "2.0 L/min",
  },

  // ─── REVERSE OSMOSIS ───────────────────────────────────────────────
  {
    id: "waterdrop-g3p600",
    brand: "Waterdrop",
    model: "G3P600 Reverse Osmosis",
    slug: "waterdrop-g3p600",
    category: "reverse_osmosis",
    removes: [
      "Lead",
      "PFAS (total)",
      "Fluoride",
      "Arsenic",
      "Nitrate",
      "Chlorine",
      "Trihalomethanes",
      "Mercury",
      "Cadmium",
      "Chromium",
      "Copper",
      "Nickel",
    ],
    certifications: ["NSF/ANSI 58", "NSF/ANSI 372"],
    priceGbp: 399,
    priceTier: "premium",
    affiliateUrl:
      "https://www.waterdropfilter.co.uk/products/waterdrop-g3p600?sca_ref=placeholder",
    affiliateProgram: "impact",
    affiliateTag: "sca_ref=placeholder",
    imageUrl: "/filters/waterdrop-g3p600.png",
    rating: 4.6,
    badge: "best-match",
    pros: [
      "Removes 12+ contaminants including PFAS and fluoride",
      "Tankless design saves under-sink space",
      "Smart TDS monitoring panel shows real-time water quality",
    ],
    cons: [
      "Professional installation recommended — plumbing required",
      "Higher upfront cost than any jug or tap filter",
      "Wastes some water during the RO process (3:1 ratio)",
    ],
    bestFor: "Maximum contaminant removal including PFAS and fluoride",
    filterLife: "12–24 months depending on stage",
    annualCost: 80,
    flowRate: "2.3 L/min",
  },
  {
    id: "frizzlife-pd600",
    brand: "Frizzlife",
    model: "PD600 Under Sink RO",
    slug: "frizzlife-pd600",
    category: "reverse_osmosis",
    removes: [
      "Lead",
      "PFAS (total)",
      "Fluoride",
      "Arsenic",
      "Nitrate",
      "Chlorine",
      "Trihalomethanes",
      "Mercury",
      "Cadmium",
      "Chromium",
    ],
    certifications: ["NSF/ANSI 58"],
    priceGbp: 329,
    priceTier: "premium",
    affiliateUrl: "https://www.amazon.co.uk/dp/B083DFW1QS?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/frizzlife-pd600.png",
    rating: 4.5,
    badge: "best-value",
    pros: [
      "Lower price than Waterdrop G3P600 with similar performance",
      "Twist-and-lock filter replacement — no tools needed",
      "600 GPD flow rate fills a glass in seconds",
    ],
    cons: [
      "Lacks the smart TDS monitoring panel",
      "Slightly noisier pump than Waterdrop",
      "Fewer certifications — NSF 58 only",
    ],
    bestFor: "Best value reverse osmosis for UK kitchens",
    filterLife: "12 months (composite filter)",
    annualCost: 70,
    flowRate: "2.3 L/min",
  },
  {
    id: "echo-water-hydrogen",
    brand: "Echo Water",
    model: "Hydrogen RO System",
    slug: "echo-water-hydrogen",
    category: "reverse_osmosis",
    removes: [
      "Lead",
      "PFAS (total)",
      "Fluoride",
      "Arsenic",
      "Nitrate",
      "Chlorine",
      "Trihalomethanes",
      "Mercury",
      "Cadmium",
      "Chromium",
      "Copper",
      "Nickel",
      "Bacteria",
    ],
    certifications: ["NSF/ANSI 58"],
    priceGbp: 499,
    priceTier: "premium",
    affiliateUrl: "https://echowater.com/?ref=tapwater",
    affiliateProgram: "impact",
    affiliateTag: "ref=tapwater",
    imageUrl: "/filters/echo-water-hydrogen.png",
    rating: 4.4,
    badge: "premium",
    pros: [
      "Adds molecular hydrogen after RO for antioxidant benefits",
      "Removes virtually all contaminants at 0.0001 micron",
      "Premium build quality with stainless steel fittings",
    ],
    cons: [
      "Most expensive option in the catalogue at £499",
      "Hydrogen benefit claims lack independent UK verification",
      "Requires professional plumbing installation",
    ],
    bestFor: "Health enthusiasts wanting the most thorough purification system",
    filterLife: "12 months",
    annualCost: 100,
    flowRate: "1.9 L/min",
  },

  // ─── WHOLE HOUSE ────────────────────────────────────────────────────
  {
    id: "bwt-e1-whole-house",
    brand: "BWT",
    model: "E1 Single Lever",
    slug: "bwt-e1-whole-house",
    category: "whole_house",
    removes: ["Sediment", "Chlorine", "Particles"],
    certifications: ["WRAS approved"],
    priceGbp: 250,
    priceTier: "mid",
    affiliateUrl: "https://www.amazon.co.uk/dp/B07D7WKPKL?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/bwt-e1.png",
    rating: 4.3,
    badge: "best-value",
    pros: [
      "WRAS approved — meets UK plumbing standards",
      "Single-lever backwash makes maintenance straightforward",
      "Protects boilers and appliances from sediment damage",
    ],
    cons: [
      "Only removes sediment and particles — not heavy metals or PFAS",
      "Requires professional installation at the mains inlet",
      "Backwash cycle wastes some water",
    ],
    bestFor: "Protecting whole-house plumbing from sediment and particles",
    filterLife: "No replacement needed — backwash cleans the filter",
    annualCost: 0,
    flowRate: "25 L/min",
  },
  {
    id: "waterdrop-whf21",
    brand: "Waterdrop",
    model: "WHF21 Whole House",
    slug: "waterdrop-whf21",
    category: "whole_house",
    removes: ["Chlorine", "Sediment", "Manganese", "Iron"],
    certifications: ["NSF/ANSI 42"],
    priceGbp: 600,
    priceTier: "premium",
    affiliateUrl:
      "https://www.waterdropfilter.co.uk/products/waterdrop-whf21?sca_ref=placeholder",
    affiliateProgram: "impact",
    affiliateTag: "sca_ref=placeholder",
    imageUrl: "/filters/waterdrop-whf21.png",
    rating: 4.5,
    badge: "best-match",
    pros: [
      "NSF 42 certified for chlorine taste and odour removal",
      "Three-stage filtration handles sediment, chemicals, and metals",
      "High 15 GPM flow rate won't reduce water pressure",
    ],
    cons: [
      "Expensive upfront cost at £600",
      "Professional installation essential — not a DIY job",
      "Replacement filter set costs around £120/year",
    ],
    bestFor: "Whole-house chlorine and iron removal for well or mains water",
    filterLife: "6 months per filter set",
    annualCost: 120,
    flowRate: "56 L/min",
  },
  {
    id: "aquasana-eq1000",
    brand: "Aquasana",
    model: "EQ-1000 Rhino",
    slug: "aquasana-eq1000",
    category: "whole_house",
    removes: ["Chlorine", "Lead", "Mercury", "Copper", "Sediment"],
    certifications: ["NSF/ANSI 42", "NSF/ANSI 61"],
    priceGbp: 800,
    priceTier: "premium",
    affiliateUrl: "https://www.amazon.co.uk/dp/B01MZGPB47?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/aquasana-eq1000.png",
    rating: 4.4,
    badge: "premium",
    pros: [
      "1,000,000-gallon capacity — lasts most homes 10 years",
      "Removes lead and mercury alongside chlorine and sediment",
      "NSF 42 + 61 dual certification for structural and taste safety",
    ],
    cons: [
      "Highest upfront cost in the whole-house category",
      "Large footprint — needs dedicated utility space",
      "Pre-filter needs replacing every 3 months",
    ],
    bestFor: "Long-term whole-house filtration for heavy metal and chlorine removal",
    filterLife: "10 years (main tank), 3 months (pre-filter)",
    annualCost: 60,
    flowRate: "26 L/min",
  },

  // ─── SHOWER ─────────────────────────────────────────────────────────
  {
    id: "jolie-filtered-showerhead",
    brand: "Jolie",
    model: "Filtered Showerhead",
    slug: "jolie-filtered-showerhead",
    category: "shower",
    removes: ["Chlorine", "Heavy metals", "Chloramine"],
    certifications: [],
    priceGbp: 85,
    priceTier: "premium",
    affiliateUrl: "https://www.amazon.co.uk/dp/B0C5QJZQY8?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/jolie-showerhead.png",
    rating: 4.5,
    badge: "premium",
    pros: [
      "Premium brushed-steel design that looks great in any bathroom",
      "KDF-55 and calcium sulphite media target chlorine and chloramine",
      "Noticeable improvement in hair and skin softness within a week",
    ],
    cons: [
      "Expensive for a showerhead at £85",
      "Filter replacement every 3 months adds ongoing cost",
      "Won't remove fluoride, PFAS, or heavy metals beyond basic levels",
    ],
    bestFor: "Anyone noticing dry skin or hair from chlorinated shower water",
    filterLife: "3 months",
    annualCost: 60,
  },
  {
    id: "aquabliss-sf220",
    brand: "AquaBliss",
    model: "SF220 Shower Filter",
    slug: "aquabliss-sf220",
    category: "shower",
    removes: ["Chlorine", "Heavy metals", "Sediment"],
    certifications: [],
    priceGbp: 25,
    priceTier: "budget",
    affiliateUrl: "https://www.amazon.co.uk/dp/B01MUBU0YC?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/aquabliss-sf220.png",
    rating: 4.2,
    badge: "budget",
    pros: [
      "Budget-friendly entry point at just £25",
      "Multi-stage sediment, KDF, and carbon block filtration",
      "Universal fit works with any standard shower arm",
    ],
    cons: [
      "Plastic housing feels less premium than Jolie",
      "Flow rate drops noticeably after 2 months",
      "Replacement cartridges can be hard to source in the UK",
    ],
    bestFor: "Affordable shower filtration for renters or first-time buyers",
    filterLife: "6 months",
    annualCost: 20,
  },
  {
    id: "philips-awp1775",
    brand: "Philips",
    model: "AWP1775 Shower Filter",
    slug: "philips-awp1775",
    category: "shower",
    removes: ["Chlorine", "Sediment"],
    certifications: [],
    priceGbp: 35,
    priceTier: "mid",
    affiliateUrl: "https://www.amazon.co.uk/dp/B0BXWNRYF4?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/philips-awp1775.png",
    rating: 4.3,
    badge: "best-value",
    pros: [
      "Trusted Philips brand with reliable build quality",
      "Activated carbon fibre media removes chlorine effectively",
      "Sleek in-line design doesn't change your showerhead",
    ],
    cons: [
      "Only removes chlorine and sediment — no heavy metals",
      "Filter cartridge is Philips-proprietary — no third-party options",
      "Slightly reduces water pressure in low-pressure systems",
    ],
    bestFor: "Mid-range chlorine removal from a brand you recognise",
    filterLife: "3 months",
    annualCost: 48,
  },

  // ─── TESTING KITS ──────────────────────────────────────────────────
  {
    id: "simplexhealth-17-in-1",
    brand: "SimplexHealth",
    model: "17-in-1 Water Test Kit",
    slug: "simplexhealth-17-in-1",
    category: "testing_kit",
    removes: [],
    certifications: [],
    priceGbp: 13,
    priceTier: "budget",
    affiliateUrl: "https://www.amazon.co.uk/dp/B0B1HMD3LH?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/simplexhealth-17.png",
    rating: 4.1,
    badge: "budget",
    pros: [
      "Tests 17 parameters including lead, pH, and hardness",
      "Results in 2 minutes with colour-match strips",
      "Cheapest way to get a quick snapshot of your water",
    ],
    cons: [
      "Strip tests are less accurate than lab analysis",
      "Colour matching can be subjective in poor lighting",
      "Does not test for PFAS or microplastics",
    ],
    bestFor: "Quick DIY screening before investing in a filter",
  },
  {
    id: "sj-wave-16-in-1",
    brand: "SJ WAVE",
    model: "16-in-1 Premium Water Test",
    slug: "sj-wave-16-in-1",
    category: "testing_kit",
    removes: [],
    certifications: [],
    priceGbp: 15,
    priceTier: "budget",
    affiliateUrl: "https://www.amazon.co.uk/dp/B0BN1JLGZP?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/sj-wave-16.png",
    rating: 4.0,
    badge: "budget",
    pros: [
      "150 strips included — enough for regular monthly testing",
      "Tests bacteria, lead, iron, copper, and more",
      "Clear colour chart printed on the bottle label",
    ],
    cons: [
      "Bacteria test requires 48-hour incubation period",
      "No digital readout — manual colour comparison only",
      "Cannot detect PFAS or pharmaceutical residues",
    ],
    bestFor: "Ongoing monthly monitoring with plenty of test strips",
  },
  {
    id: "tap-score-essential",
    brand: "Tap Score",
    model: "Essential City Water Test",
    slug: "tap-score-essential",
    category: "testing_kit",
    removes: [],
    certifications: ["ISO 17025 accredited lab"],
    priceGbp: 80,
    priceTier: "premium",
    affiliateUrl: "https://www.amazon.co.uk/dp/B07XMGKX4Q?tag=tapwater21-21",
    affiliateProgram: "amazon",
    affiliateTag: "tapwater21-21",
    imageUrl: "/filters/tap-score-essential.png",
    rating: 4.7,
    badge: "premium",
    pros: [
      "ISO 17025 accredited lab — results you can trust",
      "Tests 50+ parameters including PFAS and heavy metals",
      "Online dashboard with personalised health recommendations",
    ],
    cons: [
      "Costs £80 — significantly more than DIY strips",
      "Results take 5–7 business days to arrive",
      "Sample must be posted, so timing matters",
    ],
    bestFor: "Definitive lab-grade analysis when you want real numbers",
  },
];

/**
 * Metadata for each product category — used by category landing pages and SEO.
 */
export const CATEGORY_META: Record<
  ProductCategory,
  {
    title: string;
    slug: string;
    description: string;
    bestFor: string;
    priceRange: string;
  }
> = {
  jug: {
    title: "Water Filter Jugs",
    slug: "water-filter-jugs",
    description:
      "The simplest way to filter your tap water. Fill, wait, pour. No installation, no plumbing, no fuss.",
    bestFor: "Renters, small households, and anyone wanting a quick improvement",
    priceRange: "£20–£40",
  },
  countertop: {
    title: "Countertop & Tap Filters",
    slug: "countertop-tap-filters",
    description:
      "Clip-on or countertop filters that connect directly to your kitchen tap for on-demand filtered water.",
    bestFor: "Renters who want better filtration than a jug without permanent changes",
    priceRange: "£30–£60",
  },
  under_sink: {
    title: "Under-Sink Filters",
    slug: "under-sink-filters",
    description:
      "Hidden under your kitchen sink, these filters provide high-capacity filtration without cluttering your counter.",
    bestFor: "Homeowners wanting set-and-forget filtration with high capacity",
    priceRange: "£45–£120",
  },
  reverse_osmosis: {
    title: "Reverse Osmosis Systems",
    slug: "reverse-osmosis-systems",
    description:
      "The gold standard. RO systems push water through a semi-permeable membrane, removing virtually everything.",
    bestFor: "Households with PFAS, fluoride, or nitrate concerns",
    priceRange: "£329–£499",
  },
  whole_house: {
    title: "Whole House Filters",
    slug: "whole-house-filters",
    description:
      "Installed at the mains inlet, these systems filter every drop of water entering your home.",
    bestFor: "Homeowners wanting filtered water from every tap and shower",
    priceRange: "£250–£800",
  },
  shower: {
    title: "Shower Filters",
    slug: "shower-filters",
    description:
      "Reduce chlorine and sediment from your shower water to improve skin, hair, and breathing comfort.",
    bestFor: "Anyone with dry skin, eczema, or brittle hair from hard/chlorinated water",
    priceRange: "£25–£85",
  },
  testing_kit: {
    title: "Water Testing Kits",
    slug: "water-testing-kits",
    description:
      "Find out exactly what is in your water before deciding which filter to buy.",
    bestFor: "Anyone who wants data before spending money on filtration",
    priceRange: "£13–£80",
  },
};

/**
 * Display order for categories — most commonly purchased first.
 */
export const CATEGORY_ORDER: ProductCategory[] = [
  "jug",
  "countertop",
  "under_sink",
  "reverse_osmosis",
  "whole_house",
  "shower",
  "testing_kit",
];

/**
 * Look up products by category.
 */
export function getProductsByCategory(
  category: ProductCategory,
): FilterProduct[] {
  return PRODUCTS.filter((p) => p.category === category);
}

/**
 * Look up a single product by its URL slug.
 */
export function getProductBySlug(slug: string): FilterProduct | undefined {
  return PRODUCTS.find((p) => p.slug === slug);
}
