/**
 * Scottish Water zone-to-postcode mapping.
 *
 * Scottish Water divides its supply area into ~277 regulatory zones.
 * This mapping assigns each of Scotland's 442 postcode districts to a zone.
 *
 * Generated by scripts/build-scottish-zones-mapping.ts from zone-discovery.json.
 */

/** Maps zone name → array of postcode districts served by that zone */
export const SCOTTISH_ZONE_POSTCODES: Record<string, string[]> = {
  "Mannofield East": [
    "AB10",
    "AB11"
  ],
  "Mannofield South": [
    "AB12",
    "AB13",
    "AB14",
    "AB15",
    "AB16",
    "AB23",
    "AB24",
    "AB25"
  ],
  "Craigie": [
    "AB21",
    "AB22",
    "AB41",
    "AB51",
    "AB52",
    "AB53"
  ],
  "Whitehillocks": [
    "AB30",
    "AB31",
    "AB32",
    "AB33",
    "AB34",
    "DD10"
  ],
  "Invercannie": [
    "AB35",
    "AB36",
    "AB37",
    "AB38",
    "AB39"
  ],
  "Forehill": [
    "AB42",
    "AB43"
  ],
  "Turriff": [
    "AB44",
    "AB45",
    "AB54",
    "AB55",
    "AB56"
  ],
  "Clatto East": [
    "DD1",
    "DD2",
    "DD5",
    "DD6"
  ],
  "Clatto West_A": [
    "DD3",
    "DD4"
  ],
  "Lintrathen": [
    "DD11",
    "DD7",
    "DD8",
    "DD9"
  ],
  "Terregles": [
    "DG1",
    "DG2",
    "DG3",
    "DG4"
  ],
  "Lochinvar": [
    "DG5",
    "DG6",
    "DG7"
  ],
  "Penwhirn": [
    "DG8"
  ],
  "Auchneel": [
    "DG10",
    "DG9"
  ],
  "Black Esk": [
    "DG11",
    "DG12",
    "DG13",
    "DG14"
  ],
  "Glencorse C": [
    "EH1",
    "EH11",
    "EH2",
    "EH3"
  ],
  "Glencorse D": [
    "EH12",
    "EH14",
    "EH4"
  ],
  "Marchbank B": [
    "EH13",
    "EH5",
    "EH6",
    "EH7"
  ],
  "Glencorse B": [
    "EH10",
    "EH8",
    "EH9"
  ],
  "Glencorse_E": [
    "EH15",
    "EH16"
  ],
  "Glencorse A": [
    "EH17",
    "EH18"
  ],
  "Rosebery B": [
    "EH19",
    "EH20",
    "EH25",
    "EH26",
    "EH27",
    "EH28"
  ],
  "Rosebery A": [
    "EH21",
    "EH22",
    "EH23",
    "EH24"
  ],
  "Castle Moffat": [
    "EH29",
    "EH30",
    "EH31",
    "EH33",
    "EH34",
    "EH35",
    "EH36",
    "EH37",
    "EH38",
    "EH39",
    "EH40",
    "EH41",
    "EH42",
    "EH43",
    "EH44"
  ],
  "Rosebery Castle Moffat": [
    "EH32"
  ],
  "Pateshill": [
    "EH45",
    "EH46",
    "EH47",
    "EH48",
    "EH49"
  ],
  "Balmore E": [
    "EH51",
    "EH52"
  ],
  "Marchbank A": [
    "EH53",
    "EH54",
    "EH55"
  ],
  "Carron Valley A": [
    "FK1",
    "FK2"
  ],
  "Turret/Balmore/Carron Valley": [
    "FK3"
  ],
  "Carron Valley B": [
    "FK4",
    "FK5",
    "FK6",
    "G63",
    "G65",
    "G68"
  ],
  "Turret A": [
    "FK10",
    "FK11",
    "FK12",
    "FK13",
    "FK14",
    "FK15",
    "FK16",
    "FK17",
    "FK18",
    "FK19",
    "FK20",
    "FK21",
    "FK7",
    "FK8",
    "FK9"
  ],
  "Milngavie M3": [
    "G1",
    "G2",
    "G3",
    "G41",
    "G51"
  ],
  "Milngavie C3": [
    "G31",
    "G4"
  ],
  "Milngavie C2": [
    "G5",
    "G73"
  ],
  "Milngavie M4d": [
    "G11",
    "G12",
    "G14",
    "G15"
  ],
  "Milngavie M4c": [
    "G13",
    "G81"
  ],
  "Milngavie M1": [
    "G20",
    "G60",
    "G61",
    "G62"
  ],
  "Balmore C5 North": [
    "G21",
    "G22",
    "G23",
    "G33",
    "G64"
  ],
  "Balmore C5 South": [
    "G32",
    "G34"
  ],
  "Milngavie C4": [
    "G40"
  ],
  "Milngavie M2": [
    "G42"
  ],
  "Milngavie C1": [
    "G43",
    "G44",
    "G78"
  ],
  "Balmore Castlemilk": [
    "G45",
    "G46"
  ],
  "Milngavie M5 Drumchapel South": [
    "G52",
    "G53",
    "G58"
  ],
  "Balmore Carron Valley": [
    "G66",
    "G67"
  ],
  "Balmore A": [
    "G69",
    "G70"
  ],
  "Daer Camps B": [
    "G71",
    "G72"
  ],
  "Daer B": [
    "G74",
    "G76",
    "G77",
    "G79"
  ],
  "Camps": [
    "G75",
    "ML11",
    "ML12"
  ],
  "Blairlinnans North": [
    "G82"
  ],
  "Alexandria": [
    "G83"
  ],
  "Belmore": [
    "G84"
  ],
  "Stornoway Western Isles": [
    "HS1",
    "HS2",
    "HS3",
    "HS4",
    "HS5",
    "HS6",
    "HS7",
    "HS8",
    "HS9"
  ],
  "Inverness": [
    "IV1",
    "IV2",
    "IV3",
    "IV4",
    "IV5",
    "IV6",
    "IV7",
    "IV8",
    "IV9"
  ],
  "Assynt": [
    "IV10",
    "IV11",
    "IV12",
    "IV13",
    "IV14",
    "IV15",
    "IV16",
    "IV17"
  ],
  "Newmore": [
    "IV18",
    "IV19",
    "IV20"
  ],
  "Badachro": [
    "IV21"
  ],
  "Poolewe Regional": [
    "IV22",
    "IV23",
    "IV24",
    "IV25",
    "IV26"
  ],
  "Badentinan": [
    "IV27",
    "IV28",
    "IV30",
    "IV31",
    "IV32"
  ],
  "Spynie": [
    "IV36",
    "IV40",
    "IV41",
    "IV42",
    "IV43",
    "IV44",
    "IV45",
    "IV46",
    "IV47",
    "IV48",
    "IV49",
    "IV51",
    "IV52",
    "IV53",
    "IV54",
    "IV55",
    "IV56",
    "IV63"
  ],
  "Bradan B": [
    "KA1",
    "KA10",
    "KA2",
    "KA9"
  ],
  "Amlaird Milngavie Gorbals Zone RSZ": [
    "KA17",
    "KA3",
    "KA4",
    "KA5"
  ],
  "Bradan C": [
    "KA6",
    "KA7",
    "KA8"
  ],
  "Bradan Milngavie Gorbals Zone RSZ": [
    "KA11",
    "KA12",
    "KA13"
  ],
  "Camphill": [
    "KA14",
    "KA15",
    "KA16"
  ],
  "Afton": [
    "KA18",
    "KA19",
    "KA20",
    "KA21",
    "KA22"
  ],
  "Penwhapple": [
    "KA23",
    "KA24",
    "KA25",
    "KA26",
    "KA27"
  ],
  "Greenock": [
    "KA28",
    "KA29",
    "KA30",
    "PA13",
    "PA14",
    "PA15",
    "PA16",
    "PA17",
    "PA18",
    "PA19",
    "PA20"
  ],
  "Kirbister Orkney": [
    "KW1",
    "KW10",
    "KW11",
    "KW12",
    "KW13",
    "KW14",
    "KW15",
    "KW16",
    "KW2",
    "KW3",
    "KW5",
    "KW6",
    "KW7",
    "KW8",
    "KW9"
  ],
  "Eday Orkney": [
    "KW17"
  ],
  "GLENFARG KWOODBH B": [
    "KY1",
    "KY2"
  ],
  "Glendevon B": [
    "KY11",
    "KY3",
    "KY4",
    "KY5"
  ],
  "GLENFARG KWOODBH A": [
    "KY6",
    "KY7",
    "KY8"
  ],
  "Glendevon/Glenfarg": [
    "KY10",
    "KY9"
  ],
  "Glendevon A": [
    "KY12",
    "KY13",
    "KY14"
  ],
  "Lomond Hills BH Mix": [
    "KY15",
    "KY16"
  ],
  "Balmore Legbrannock": [
    "ML1"
  ],
  "Daer A": [
    "ML2"
  ],
  "Daer C": [
    "ML3"
  ],
  "Balmore B": [
    "ML4",
    "ML5"
  ],
  "Balmore C": [
    "ML6",
    "ML7"
  ],
  "Daer Camps A": [
    "ML10",
    "ML8",
    "ML9"
  ],
  "Blairlinnans South": [
    "PA1",
    "PA3"
  ],
  "Muirdykes": [
    "PA10",
    "PA11",
    "PA12",
    "PA2",
    "PA5",
    "PA6",
    "PA7",
    "PA8",
    "PA9"
  ],
  "Milngavie M5 Drumchapel North": [
    "PA4"
  ],
  "Tighnabruaich": [
    "PA21",
    "PA22",
    "PA23",
    "PA24",
    "PA25",
    "PA26",
    "PA27"
  ],
  "Dalmally": [
    "PA28",
    "PA29",
    "PA30",
    "PA31",
    "PA32",
    "PA33",
    "PA34"
  ],
  "Taynuilt": [
    "PA35",
    "PA36"
  ],
  "Tullich": [
    "PA37",
    "PA38",
    "PA41",
    "PA42",
    "PA43",
    "PA44",
    "PA45",
    "PA46",
    "PA47",
    "PA48",
    "PA49",
    "PA60",
    "PA61",
    "PA62",
    "PA63",
    "PA64",
    "PA65",
    "PA66",
    "PA67",
    "PA68",
    "PA69",
    "PA70",
    "PA71",
    "PA72",
    "PA73",
    "PA74",
    "PA75",
    "PA76",
    "PA77",
    "PA78",
    "PA80"
  ],
  "Perth": [
    "PH1",
    "PH10",
    "PH11",
    "PH2",
    "PH7",
    "PH8",
    "PH9"
  ],
  "Turret B": [
    "PH3",
    "PH4",
    "PH5",
    "PH6"
  ],
  "Killiecrankie": [
    "PH12",
    "PH13",
    "PH14",
    "PH15",
    "PH16",
    "PH17"
  ],
  "Dalwhinnie": [
    "PH18",
    "PH19"
  ],
  "Aviemore": [
    "PH20",
    "PH21",
    "PH22",
    "PH23",
    "PH24",
    "PH25",
    "PH26",
    "PH30",
    "PH31",
    "PH32",
    "PH33",
    "PH34",
    "PH35",
    "PH36",
    "PH37",
    "PH38",
    "PH39",
    "PH40",
    "PH41",
    "PH42",
    "PH43",
    "PH44",
    "PH49",
    "PH50"
  ],
  "Manse Street": [
    "TD1",
    "TD2",
    "TD3"
  ],
  "Howden": [
    "TD10",
    "TD11",
    "TD13",
    "TD14",
    "TD4",
    "TD6",
    "TD7",
    "TD8"
  ],
  "Lerwick Shetland": [
    "ZE1",
    "ZE2",
    "ZE3"
  ]
};

/** Maps zone name → URL slug (for PDF downloads) */
export const SCOTTISH_ZONE_SLUGS: Record<string, string> = {
  "Mannofield East": "mannofield-east",
  "Mannofield South": "mannofield-south",
  "Craigie": "craigie",
  "Whitehillocks": "whitehillocks",
  "Invercannie": "invercannie",
  "Forehill": "forehill",
  "Turriff": "turriff",
  "Clatto East": "clatto-east",
  "Clatto West_A": "clatto-west_a",
  "Lintrathen": "lintrathen",
  "Terregles": "terregles",
  "Lochinvar": "lochinvar",
  "Penwhirn": "penwhirn",
  "Auchneel": "auchneel",
  "Black Esk": "black-esk",
  "Glencorse C": "glencorse-c",
  "Glencorse D": "glencorse-d",
  "Marchbank B": "marchbank-b",
  "Glencorse B": "glencorse-b",
  "Glencorse_E": "glencorse_e",
  "Glencorse A": "glencorse-a",
  "Rosebery B": "rosebery-b",
  "Rosebery A": "rosebery-a",
  "Castle Moffat": "castle-moffat",
  "Rosebery Castle Moffat": "rosebery-castle-moffat",
  "Pateshill": "pateshill",
  "Balmore E": "balmore-e",
  "Marchbank A": "marchbank-a",
  "Carron Valley A": "carron-valley-a",
  "Turret/Balmore/Carron Valley": "turret/balmore/carron-valley",
  "Carron Valley B": "carron-valley-b",
  "Turret A": "turret-a",
  "Milngavie M3": "milngavie-m3",
  "Milngavie C3": "milngavie-c3",
  "Milngavie C2": "milngavie-c2",
  "Milngavie M4d": "milngavie-m4d",
  "Milngavie M4c": "milngavie-m4c",
  "Milngavie M1": "milngavie-m1",
  "Balmore C5 North": "balmore-c5-north",
  "Balmore C5 South": "balmore-c5-south",
  "Milngavie C4": "milngavie-c4",
  "Milngavie M2": "milngavie-m2",
  "Milngavie C1": "milngavie-c1",
  "Balmore Castlemilk": "balmore-castlemilk",
  "Milngavie M5 Drumchapel South": "milngavie-m5-drumchapel-south",
  "Balmore Carron Valley": "balmore-carron-valley",
  "Balmore A": "balmore-a",
  "Daer Camps B": "daer-camps-b",
  "Daer B": "daer-b",
  "Camps": "camps",
  "Blairlinnans North": "blairlinnans-north",
  "Alexandria": "alexandria",
  "Belmore": "belmore",
  "Stornoway Western Isles": "stornoway-western-isles",
  "Inverness": "inverness",
  "Assynt": "assynt",
  "Newmore": "newmore",
  "Badachro": "badachro",
  "Poolewe Regional": "poolewe-regional",
  "Badentinan": "badentinan",
  "Spynie": "spynie",
  "Bradan B": "bradan-b",
  "Amlaird Milngavie Gorbals Zone RSZ": "amlaird-milngavie-gorbals-zone-rsz",
  "Bradan C": "bradan-c",
  "Bradan Milngavie Gorbals Zone RSZ": "bradan-milngavie-gorbals-zone-rsz",
  "Camphill": "camphill",
  "Afton": "afton",
  "Penwhapple": "penwhapple",
  "Greenock": "greenock",
  "Kirbister Orkney": "kirbister-orkney",
  "Eday Orkney": "eday-orkney",
  "GLENFARG KWOODBH B": "glenfarg-kwoodbh-b",
  "Glendevon B": "glendevon-b",
  "GLENFARG KWOODBH A": "glenfarg-kwoodbh-a",
  "Glendevon/Glenfarg": "glendevon/glenfarg",
  "Glendevon A": "glendevon-a",
  "Lomond Hills BH Mix": "lomond-hills-bh-mix",
  "Balmore Legbrannock": "balmore-legbrannock",
  "Daer A": "daer-a",
  "Daer C": "daer-c",
  "Balmore B": "balmore-b",
  "Balmore C": "balmore-c",
  "Daer Camps A": "daer-camps-a",
  "Blairlinnans South": "blairlinnans-south",
  "Muirdykes": "muirdykes",
  "Milngavie M5 Drumchapel North": "milngavie-m5-drumchapel-north",
  "Tighnabruaich": "tighnabruaich",
  "Dalmally": "dalmally",
  "Taynuilt": "taynuilt",
  "Tullich": "tullich",
  "Perth": "perth",
  "Turret B": "turret-b",
  "Killiecrankie": "killiecrankie",
  "Dalwhinnie": "dalwhinnie",
  "Aviemore": "aviemore",
  "Manse Street": "manse-street",
  "Howden": "howden",
  "Lerwick Shetland": "lerwick-shetland"
};

/**
 * Look up which Scottish Water zone a postcode district belongs to.
 * Returns null if the postcode is not in Scotland.
 */
export function getScottishZone(district: string): string | null {
  for (const [zone, postcodes] of Object.entries(SCOTTISH_ZONE_POSTCODES)) {
    if (postcodes.includes(district)) return zone;
  }
  return null;
}

/**
 * Check if a postcode district is served by Scottish Water.
 */
export function isScottishPostcode(district: string): boolean {
  return getScottishZone(district) !== null;
}
