/**
 * Water supplier mapping for TapWater.uk
 * Maps local authority area names to water companies.
 * Shared between the data pipeline and the data layer.
 */

export interface SupplierInfo {
  name: string;
  id: string;
}

export const SUPPLIER_MAP: Record<string, SupplierInfo> = {
  // ─── Thames Water ────────────────────────────────────────────────────────────
  // London boroughs
  Westminster: { name: "Thames Water", id: "thames-water" },
  Southwark: { name: "Thames Water", id: "thames-water" },
  Greenwich: { name: "Thames Water", id: "thames-water" },
  Hackney: { name: "Thames Water", id: "thames-water" },
  "Tower Hamlets": { name: "Thames Water", id: "thames-water" },
  Camden: { name: "Thames Water", id: "thames-water" },
  "Kensington and Chelsea": { name: "Thames Water", id: "thames-water" },
  "Hammersmith and Fulham": { name: "Thames Water", id: "thames-water" },
  Barnet: { name: "Thames Water", id: "thames-water" },
  "Barking and Dagenham": { name: "Thames Water", id: "thames-water" },
  Bexley: { name: "Thames Water", id: "thames-water" },
  Brent: { name: "Thames Water", id: "thames-water" },
  Bromley: { name: "Thames Water", id: "thames-water" },
  "City of London": { name: "Thames Water", id: "thames-water" },
  Croydon: { name: "Thames Water", id: "thames-water" },
  Ealing: { name: "Thames Water", id: "thames-water" },
  Enfield: { name: "Thames Water", id: "thames-water" },
  Haringey: { name: "Thames Water", id: "thames-water" },
  Harrow: { name: "Thames Water", id: "thames-water" },
  Havering: { name: "Thames Water", id: "thames-water" },
  Hillingdon: { name: "Thames Water", id: "thames-water" },
  Hounslow: { name: "Thames Water", id: "thames-water" },
  Islington: { name: "Thames Water", id: "thames-water" },
  "Kingston upon Thames": { name: "Thames Water", id: "thames-water" },
  Lambeth: { name: "Thames Water", id: "thames-water" },
  Lewisham: { name: "Thames Water", id: "thames-water" },
  Merton: { name: "Thames Water", id: "thames-water" },
  Newham: { name: "Thames Water", id: "thames-water" },
  Redbridge: { name: "Thames Water", id: "thames-water" },
  "Richmond upon Thames": { name: "Thames Water", id: "thames-water" },
  Sutton: { name: "Thames Water", id: "thames-water" },
  "Waltham Forest": { name: "Thames Water", id: "thames-water" },
  Wandsworth: { name: "Thames Water", id: "thames-water" },
  // Thames Valley
  Oxford: { name: "Thames Water", id: "thames-water" },
  "South Oxfordshire": { name: "Thames Water", id: "thames-water" },
  "Vale of White Horse": { name: "Thames Water", id: "thames-water" },
  Reading: { name: "Thames Water", id: "thames-water" },
  "West Berkshire": { name: "Thames Water", id: "thames-water" },
  Wokingham: { name: "Thames Water", id: "thames-water" },
  "Bracknell Forest": { name: "Thames Water", id: "thames-water" },
  "Windsor and Maidenhead": { name: "Thames Water", id: "thames-water" },
  Slough: { name: "Thames Water", id: "thames-water" },
  Spelthorne: { name: "Thames Water", id: "thames-water" },
  Runnymede: { name: "Thames Water", id: "thames-water" },
  Elmbridge: { name: "Thames Water", id: "thames-water" },
  "Epsom and Ewell": { name: "Thames Water", id: "thames-water" },
  "Mole Valley": { name: "Thames Water", id: "thames-water" },
  "Reigate and Banstead": { name: "Thames Water", id: "thames-water" },
  Tandridge: { name: "Thames Water", id: "thames-water" },
  "Surrey Heath": { name: "Thames Water", id: "thames-water" },
  Woking: { name: "Thames Water", id: "thames-water" },
  Guildford: { name: "Thames Water", id: "thames-water" },
  Waverley: { name: "Thames Water", id: "thames-water" },
  Cherwell: { name: "Thames Water", id: "thames-water" },
  "West Oxfordshire": { name: "Thames Water", id: "thames-water" },
  Swindon: { name: "Thames Water", id: "thames-water" },
  Wiltshire: { name: "Thames Water", id: "thames-water" },
  "Aylesbury Vale": { name: "Thames Water", id: "thames-water" },
  Wycombe: { name: "Thames Water", id: "thames-water" },
  "South Bucks": { name: "Thames Water", id: "thames-water" },
  Chiltern: { name: "Thames Water", id: "thames-water" },
  Dacorum: { name: "Thames Water", id: "thames-water" },
  "Three Rivers": { name: "Thames Water", id: "thames-water" },
  Watford: { name: "Thames Water", id: "thames-water" },
  Hertsmere: { name: "Thames Water", id: "thames-water" },
  "St Albans": { name: "Thames Water", id: "thames-water" },
  "Welwyn Hatfield": { name: "Thames Water", id: "thames-water" },
  Broxbourne: { name: "Thames Water", id: "thames-water" },
  Luton: { name: "Thames Water", id: "thames-water" },
  "Central Bedfordshire": { name: "Thames Water", id: "thames-water" },

  // ─── United Utilities ────────────────────────────────────────────────────────
  Manchester: { name: "United Utilities", id: "united-utilities" },
  Salford: { name: "United Utilities", id: "united-utilities" },
  Trafford: { name: "United Utilities", id: "united-utilities" },
  Stockport: { name: "United Utilities", id: "united-utilities" },
  Tameside: { name: "United Utilities", id: "united-utilities" },
  Oldham: { name: "United Utilities", id: "united-utilities" },
  Rochdale: { name: "United Utilities", id: "united-utilities" },
  Bury: { name: "United Utilities", id: "united-utilities" },
  Bolton: { name: "United Utilities", id: "united-utilities" },
  Wigan: { name: "United Utilities", id: "united-utilities" },
  Liverpool: { name: "United Utilities", id: "united-utilities" },
  Sefton: { name: "United Utilities", id: "united-utilities" },
  Knowsley: { name: "United Utilities", id: "united-utilities" },
  "St Helens": { name: "United Utilities", id: "united-utilities" },
  Wirral: { name: "United Utilities", id: "united-utilities" },
  Halton: { name: "United Utilities", id: "united-utilities" },
  Warrington: { name: "United Utilities", id: "united-utilities" },
  "Cheshire East": { name: "United Utilities", id: "united-utilities" },
  "Cheshire West and Chester": { name: "United Utilities", id: "united-utilities" },
  Blackpool: { name: "United Utilities", id: "united-utilities" },
  "Blackburn with Darwen": { name: "United Utilities", id: "united-utilities" },
  Burnley: { name: "United Utilities", id: "united-utilities" },
  Pendle: { name: "United Utilities", id: "united-utilities" },
  Rossendale: { name: "United Utilities", id: "united-utilities" },
  Hyndburn: { name: "United Utilities", id: "united-utilities" },
  "Ribble Valley": { name: "United Utilities", id: "united-utilities" },
  "South Ribble": { name: "United Utilities", id: "united-utilities" },
  Chorley: { name: "United Utilities", id: "united-utilities" },
  Preston: { name: "United Utilities", id: "united-utilities" },
  "West Lancashire": { name: "United Utilities", id: "united-utilities" },
  Lancaster: { name: "United Utilities", id: "united-utilities" },
  Fylde: { name: "United Utilities", id: "united-utilities" },
  Wyre: { name: "United Utilities", id: "united-utilities" },
  "Barrow-in-Furness": { name: "United Utilities", id: "united-utilities" },
  "South Lakeland": { name: "United Utilities", id: "united-utilities" },
  Eden: { name: "United Utilities", id: "united-utilities" },
  Allerdale: { name: "United Utilities", id: "united-utilities" },
  Copeland: { name: "United Utilities", id: "united-utilities" },
  Carlisle: { name: "United Utilities", id: "united-utilities" },

  // ─── Severn Trent ────────────────────────────────────────────────────────────
  Birmingham: { name: "Severn Trent", id: "severn-trent" },
  Solihull: { name: "Severn Trent", id: "severn-trent" },
  Sandwell: { name: "Severn Trent", id: "severn-trent" },
  Dudley: { name: "Severn Trent", id: "severn-trent" },
  Wolverhampton: { name: "Severn Trent", id: "severn-trent" },
  Walsall: { name: "Severn Trent", id: "severn-trent" },
  Coventry: { name: "Severn Trent", id: "severn-trent" },
  Warwick: { name: "Severn Trent", id: "severn-trent" },
  "Stratford-on-Avon": { name: "Severn Trent", id: "severn-trent" },
  Rugby: { name: "Severn Trent", id: "severn-trent" },
  "Nuneaton and Bedworth": { name: "Severn Trent", id: "severn-trent" },
  "North Warwickshire": { name: "Severn Trent", id: "severn-trent" },
  Nottingham: { name: "Severn Trent", id: "severn-trent" },
  Gedling: { name: "Severn Trent", id: "severn-trent" },
  Rushcliffe: { name: "Severn Trent", id: "severn-trent" },
  Broxtowe: { name: "Severn Trent", id: "severn-trent" },
  Ashfield: { name: "Severn Trent", id: "severn-trent" },
  Mansfield: { name: "Severn Trent", id: "severn-trent" },
  "Newark and Sherwood": { name: "Severn Trent", id: "severn-trent" },
  Bassetlaw: { name: "Severn Trent", id: "severn-trent" },
  Leicester: { name: "Severn Trent", id: "severn-trent" },
  Charnwood: { name: "Severn Trent", id: "severn-trent" },
  Blaby: { name: "Severn Trent", id: "severn-trent" },
  "Oadby and Wigston": { name: "Severn Trent", id: "severn-trent" },
  Harborough: { name: "Severn Trent", id: "severn-trent" },
  "Hinckley and Bosworth": { name: "Severn Trent", id: "severn-trent" },
  "North West Leicestershire": { name: "Severn Trent", id: "severn-trent" },
  Melton: { name: "Severn Trent", id: "severn-trent" },
  Derby: { name: "Severn Trent", id: "severn-trent" },
  "South Derbyshire": { name: "Severn Trent", id: "severn-trent" },
  Erewash: { name: "Severn Trent", id: "severn-trent" },
  "Amber Valley": { name: "Severn Trent", id: "severn-trent" },
  "North East Derbyshire": { name: "Severn Trent", id: "severn-trent" },
  Bolsover: { name: "Severn Trent", id: "severn-trent" },
  "Derbyshire Dales": { name: "Severn Trent", id: "severn-trent" },
  "High Peak": { name: "Severn Trent", id: "severn-trent" },
  "Stoke-on-Trent": { name: "Severn Trent", id: "severn-trent" },
  Stafford: { name: "Severn Trent", id: "severn-trent" },
  "East Staffordshire": { name: "Severn Trent", id: "severn-trent" },
  "South Staffordshire": { name: "Severn Trent", id: "severn-trent" },
  Lichfield: { name: "Severn Trent", id: "severn-trent" },
  Tamworth: { name: "Severn Trent", id: "severn-trent" },
  "Cannock Chase": { name: "Severn Trent", id: "severn-trent" },
  "Newcastle-under-Lyme": { name: "Severn Trent", id: "severn-trent" },
  "Staffordshire Moorlands": { name: "Severn Trent", id: "severn-trent" },
  "Telford and Wrekin": { name: "Severn Trent", id: "severn-trent" },
  Shropshire: { name: "Severn Trent", id: "severn-trent" },
  Herefordshire: { name: "Severn Trent", id: "severn-trent" },
  Worcester: { name: "Severn Trent", id: "severn-trent" },
  "Malvern Hills": { name: "Severn Trent", id: "severn-trent" },
  Wychavon: { name: "Severn Trent", id: "severn-trent" },
  Bromsgrove: { name: "Severn Trent", id: "severn-trent" },
  Redditch: { name: "Severn Trent", id: "severn-trent" },
  "Wyre Forest": { name: "Severn Trent", id: "severn-trent" },

  // ─── Yorkshire Water ─────────────────────────────────────────────────────────
  Leeds: { name: "Yorkshire Water", id: "yorkshire-water" },
  Bradford: { name: "Yorkshire Water", id: "yorkshire-water" },
  Wakefield: { name: "Yorkshire Water", id: "yorkshire-water" },
  Calderdale: { name: "Yorkshire Water", id: "yorkshire-water" },
  Kirklees: { name: "Yorkshire Water", id: "yorkshire-water" },
  Sheffield: { name: "Yorkshire Water", id: "yorkshire-water" },
  Rotherham: { name: "Yorkshire Water", id: "yorkshire-water" },
  Barnsley: { name: "Yorkshire Water", id: "yorkshire-water" },
  Doncaster: { name: "Yorkshire Water", id: "yorkshire-water" },
  York: { name: "Yorkshire Water", id: "yorkshire-water" },
  Selby: { name: "Yorkshire Water", id: "yorkshire-water" },
  Harrogate: { name: "Yorkshire Water", id: "yorkshire-water" },
  Craven: { name: "Yorkshire Water", id: "yorkshire-water" },
  Richmondshire: { name: "Yorkshire Water", id: "yorkshire-water" },
  Hambleton: { name: "Yorkshire Water", id: "yorkshire-water" },
  Ryedale: { name: "Yorkshire Water", id: "yorkshire-water" },
  Scarborough: { name: "Yorkshire Water", id: "yorkshire-water" },
  "East Riding of Yorkshire": { name: "Yorkshire Water", id: "yorkshire-water" },
  "Kingston upon Hull": { name: "Yorkshire Water", id: "yorkshire-water" },

  // ─── Anglian Water ───────────────────────────────────────────────────────────
  Cambridge: { name: "Anglian Water", id: "anglian-water" },
  "South Cambridgeshire": { name: "Anglian Water", id: "anglian-water" },
  "East Cambridgeshire": { name: "Anglian Water", id: "anglian-water" },
  Fenland: { name: "Anglian Water", id: "anglian-water" },
  Huntingdonshire: { name: "Anglian Water", id: "anglian-water" },
  Peterborough: { name: "Anglian Water", id: "anglian-water" },
  Norwich: { name: "Anglian Water", id: "anglian-water" },
  "South Norfolk": { name: "Anglian Water", id: "anglian-water" },
  "North Norfolk": { name: "Anglian Water", id: "anglian-water" },
  Breckland: { name: "Anglian Water", id: "anglian-water" },
  Broadland: { name: "Anglian Water", id: "anglian-water" },
  "Great Yarmouth": { name: "Anglian Water", id: "anglian-water" },
  "King's Lynn and West Norfolk": { name: "Anglian Water", id: "anglian-water" },
  Ipswich: { name: "Anglian Water", id: "anglian-water" },
  Babergh: { name: "Anglian Water", id: "anglian-water" },
  "Mid Suffolk": { name: "Anglian Water", id: "anglian-water" },
  "East Suffolk": { name: "Anglian Water", id: "anglian-water" },
  "West Suffolk": { name: "Anglian Water", id: "anglian-water" },
  Lincoln: { name: "Anglian Water", id: "anglian-water" },
  "North Kesteven": { name: "Anglian Water", id: "anglian-water" },
  "South Kesteven": { name: "Anglian Water", id: "anglian-water" },
  "West Lindsey": { name: "Anglian Water", id: "anglian-water" },
  "East Lindsey": { name: "Anglian Water", id: "anglian-water" },
  Boston: { name: "Anglian Water", id: "anglian-water" },
  "South Holland": { name: "Anglian Water", id: "anglian-water" },
  "North Northamptonshire": { name: "Anglian Water", id: "anglian-water" },
  "West Northamptonshire": { name: "Anglian Water", id: "anglian-water" },
  Bedford: { name: "Anglian Water", id: "anglian-water" },
  Colchester: { name: "Anglian Water", id: "anglian-water" },
  Tendring: { name: "Anglian Water", id: "anglian-water" },
  Braintree: { name: "Anglian Water", id: "anglian-water" },
  Uttlesford: { name: "Anglian Water", id: "anglian-water" },
  Chelmsford: { name: "Anglian Water", id: "anglian-water" },
  Maldon: { name: "Anglian Water", id: "anglian-water" },
  Basildon: { name: "Anglian Water", id: "anglian-water" },
  Thurrock: { name: "Anglian Water", id: "anglian-water" },
  "Southend-on-Sea": { name: "Anglian Water", id: "anglian-water" },
  Rochford: { name: "Anglian Water", id: "anglian-water" },
  "Castle Point": { name: "Anglian Water", id: "anglian-water" },

  // ─── Southern Water ──────────────────────────────────────────────────────────
  "Brighton and Hove": { name: "Southern Water", id: "southern-water" },
  Worthing: { name: "Southern Water", id: "southern-water" },
  Adur: { name: "Southern Water", id: "southern-water" },
  Arun: { name: "Southern Water", id: "southern-water" },
  Chichester: { name: "Southern Water", id: "southern-water" },
  Horsham: { name: "Southern Water", id: "southern-water" },
  "Mid Sussex": { name: "Southern Water", id: "southern-water" },
  Lewes: { name: "Southern Water", id: "southern-water" },
  Wealden: { name: "Southern Water", id: "southern-water" },
  Eastbourne: { name: "Southern Water", id: "southern-water" },
  Hastings: { name: "Southern Water", id: "southern-water" },
  Rother: { name: "Southern Water", id: "southern-water" },
  Southampton: { name: "Southern Water", id: "southern-water" },
  Eastleigh: { name: "Southern Water", id: "southern-water" },
  "Test Valley": { name: "Southern Water", id: "southern-water" },
  Winchester: { name: "Southern Water", id: "southern-water" },
  "New Forest": { name: "Southern Water", id: "southern-water" },
  Fareham: { name: "Southern Water", id: "southern-water" },
  Gosport: { name: "Southern Water", id: "southern-water" },
  Havant: { name: "Southern Water", id: "southern-water" },
  "Isle of Wight": { name: "Southern Water", id: "southern-water" },
  "Folkestone and Hythe": { name: "Southern Water", id: "southern-water" },
  Dover: { name: "Southern Water", id: "southern-water" },
  Canterbury: { name: "Southern Water", id: "southern-water" },
  Thanet: { name: "Southern Water", id: "southern-water" },
  Ashford: { name: "Southern Water", id: "southern-water" },
  Maidstone: { name: "Southern Water", id: "southern-water" },
  Medway: { name: "Southern Water", id: "southern-water" },
  Swale: { name: "Southern Water", id: "southern-water" },
  "Tonbridge and Malling": { name: "Southern Water", id: "southern-water" },
  Gravesham: { name: "Southern Water", id: "southern-water" },
  Dartford: { name: "Thames Water", id: "thames-water" },
  Sevenoaks: { name: "South East Water", id: "south-east-water" },
  "Tunbridge Wells": { name: "South East Water", id: "south-east-water" },

  // ─── South West Water ────────────────────────────────────────────────────────
  Exeter: { name: "South West Water", id: "south-west-water" },
  "East Devon": { name: "South West Water", id: "south-west-water" },
  "Mid Devon": { name: "South West Water", id: "south-west-water" },
  "North Devon": { name: "South West Water", id: "south-west-water" },
  Torridge: { name: "South West Water", id: "south-west-water" },
  "West Devon": { name: "South West Water", id: "south-west-water" },
  "South Hams": { name: "South West Water", id: "south-west-water" },
  Teignbridge: { name: "South West Water", id: "south-west-water" },
  Plymouth: { name: "South West Water", id: "south-west-water" },
  Cornwall: { name: "South West Water", id: "south-west-water" },
  "Isles of Scilly": { name: "South West Water", id: "south-west-water" },

  // ─── Northumbrian Water ──────────────────────────────────────────────────────
  "Newcastle upon Tyne": { name: "Northumbrian Water", id: "northumbrian-water" },
  Gateshead: { name: "Northumbrian Water", id: "northumbrian-water" },
  "South Tyneside": { name: "Northumbrian Water", id: "northumbrian-water" },
  "North Tyneside": { name: "Northumbrian Water", id: "northumbrian-water" },
  Sunderland: { name: "Northumbrian Water", id: "northumbrian-water" },
  Durham: { name: "Northumbrian Water", id: "northumbrian-water" },
  Darlington: { name: "Northumbrian Water", id: "northumbrian-water" },
  Hartlepool: { name: "Northumbrian Water", id: "northumbrian-water" },
  "Stockton-on-Tees": { name: "Northumbrian Water", id: "northumbrian-water" },
  Middlesbrough: { name: "Northumbrian Water", id: "northumbrian-water" },
  "Redcar and Cleveland": { name: "Northumbrian Water", id: "northumbrian-water" },
  Northumberland: { name: "Northumbrian Water", id: "northumbrian-water" },

  // ─── Welsh Water / Dŵr Cymru ─────────────────────────────────────────────────
  Cardiff: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Swansea: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Newport: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  "Vale of Glamorgan": { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Bridgend: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  "Rhondda Cynon Taf": { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  "Merthyr Tydfil": { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Caerphilly: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  "Blaenau Gwent": { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Torfaen: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Monmouthshire: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  "Neath Port Talbot": { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Carmarthenshire: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Pembrokeshire: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Ceredigion: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Powys: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Gwynedd: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  "Isle of Anglesey": { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Conwy: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Denbighshire: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Flintshire: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },
  Wrexham: { name: "Dŵr Cymru Welsh Water", id: "welsh-water" },

  // ─── Scottish Water ──────────────────────────────────────────────────────────
  "City of Edinburgh": { name: "Scottish Water", id: "scottish-water" },
  Glasgow: { name: "Scottish Water", id: "scottish-water" },
  "Glasgow City": { name: "Scottish Water", id: "scottish-water" },
  "Aberdeen City": { name: "Scottish Water", id: "scottish-water" },
  "Dundee City": { name: "Scottish Water", id: "scottish-water" },
  Fife: { name: "Scottish Water", id: "scottish-water" },
  "South Lanarkshire": { name: "Scottish Water", id: "scottish-water" },
  "North Lanarkshire": { name: "Scottish Water", id: "scottish-water" },
  Renfrewshire: { name: "Scottish Water", id: "scottish-water" },
  "East Renfrewshire": { name: "Scottish Water", id: "scottish-water" },
  Inverclyde: { name: "Scottish Water", id: "scottish-water" },
  "West Dunbartonshire": { name: "Scottish Water", id: "scottish-water" },
  "East Dunbartonshire": { name: "Scottish Water", id: "scottish-water" },
  Falkirk: { name: "Scottish Water", id: "scottish-water" },
  Stirling: { name: "Scottish Water", id: "scottish-water" },
  Clackmannanshire: { name: "Scottish Water", id: "scottish-water" },
  "Perth and Kinross": { name: "Scottish Water", id: "scottish-water" },
  Angus: { name: "Scottish Water", id: "scottish-water" },
  Highland: { name: "Scottish Water", id: "scottish-water" },
  Moray: { name: "Scottish Water", id: "scottish-water" },
  "Argyll and Bute": { name: "Scottish Water", id: "scottish-water" },
  Aberdeenshire: { name: "Scottish Water", id: "scottish-water" },
  "East Lothian": { name: "Scottish Water", id: "scottish-water" },
  Midlothian: { name: "Scottish Water", id: "scottish-water" },
  "West Lothian": { name: "Scottish Water", id: "scottish-water" },
  "Scottish Borders": { name: "Scottish Water", id: "scottish-water" },
  "Dumfries and Galloway": { name: "Scottish Water", id: "scottish-water" },
  "North Ayrshire": { name: "Scottish Water", id: "scottish-water" },
  "East Ayrshire": { name: "Scottish Water", id: "scottish-water" },
  "South Ayrshire": { name: "Scottish Water", id: "scottish-water" },
  "Shetland Islands": { name: "Scottish Water", id: "scottish-water" },
  "Orkney Islands": { name: "Scottish Water", id: "scottish-water" },
  "Na h-Eileanan Siar": { name: "Scottish Water", id: "scottish-water" },

  // ─── Bristol Water ───────────────────────────────────────────────────────────
  "Bristol, City of": { name: "Bristol Water", id: "bristol-water" },
  "North Somerset": { name: "Bristol Water", id: "bristol-water" },
  "South Gloucestershire": { name: "Bristol Water", id: "bristol-water" },

  // ─── Wessex Water ────────────────────────────────────────────────────────────
  "Bath and North East Somerset": { name: "Wessex Water", id: "wessex-water" },
  Somerset: { name: "Wessex Water", id: "wessex-water" },
  "South Somerset": { name: "Wessex Water", id: "wessex-water" },
  Mendip: { name: "Wessex Water", id: "wessex-water" },
  Sedgemoor: { name: "Wessex Water", id: "wessex-water" },
  Dorset: { name: "Wessex Water", id: "wessex-water" },
  "North Dorset": { name: "Wessex Water", id: "wessex-water" },
  "West Dorset": { name: "Wessex Water", id: "wessex-water" },
  "Weymouth and Portland": { name: "Wessex Water", id: "wessex-water" },
  Purbeck: { name: "Wessex Water", id: "wessex-water" },
  Christchurch: { name: "Wessex Water", id: "wessex-water" },

  // ─── Portsmouth Water ────────────────────────────────────────────────────────
  Portsmouth: { name: "Portsmouth Water", id: "portsmouth-water" },

  // ─── Affinity Water ──────────────────────────────────────────────────────────
  "East Hertfordshire": { name: "Affinity Water", id: "affinity-water" },
  "North Hertfordshire": { name: "Affinity Water", id: "affinity-water" },
  Stevenage: { name: "Affinity Water", id: "affinity-water" },
  Harlow: { name: "Affinity Water", id: "affinity-water" },
  "Epping Forest": { name: "Affinity Water", id: "affinity-water" },
  Brentwood: { name: "Affinity Water", id: "affinity-water" },

  // ─── South East Water ────────────────────────────────────────────────────────
  Crawley: { name: "South East Water", id: "south-east-water" },

  // ── 2023 Local Government Reorganisation ──────────────────────────────────
  // These unitary authorities replaced older district councils.
  // postcodes.io now returns these names instead of the old ones.

  // Yorkshire Water
  "North Yorkshire": { name: "Yorkshire Water", id: "yorkshire-water" },
  "Kingston upon Hull, City of": { name: "Yorkshire Water", id: "yorkshire-water" },

  // United Utilities
  Cumberland: { name: "United Utilities", id: "united-utilities" },
  "Westmorland and Furness": { name: "United Utilities", id: "united-utilities" },
  "St. Helens": { name: "United Utilities", id: "united-utilities" },

  // Anglian Water
  "Milton Keynes": { name: "Anglian Water", id: "anglian-water" },
  "North Lincolnshire": { name: "Anglian Water", id: "anglian-water" },
  "North East Lincolnshire": { name: "Anglian Water", id: "anglian-water" },

  // Thames Water
  Buckinghamshire: { name: "Thames Water", id: "thames-water" },

  // Severn Trent
  "Herefordshire, County of": { name: "Severn Trent", id: "severn-trent" },
  Tewkesbury: { name: "Severn Trent", id: "severn-trent" },
  Stroud: { name: "Severn Trent", id: "severn-trent" },
  Gloucester: { name: "Severn Trent", id: "severn-trent" },
  Cheltenham: { name: "Severn Trent", id: "severn-trent" },
  Cotswold: { name: "Severn Trent", id: "severn-trent" },
  "Forest of Dean": { name: "Severn Trent", id: "severn-trent" },

  // Wessex Water
  "Bournemouth, Christchurch and Poole": { name: "Wessex Water", id: "wessex-water" },

  // Southern Water
  Hart: { name: "Southern Water", id: "southern-water" },
  "East Hampshire": { name: "Southern Water", id: "southern-water" },
  "Basingstoke and Deane": { name: "Southern Water", id: "southern-water" },
  Rushmoor: { name: "Southern Water", id: "southern-water" },

  // Northumbrian Water
  "County Durham": { name: "Northumbrian Water", id: "northumbrian-water" },

  // NI Water — all 11 Northern Ireland local government districts
  "Antrim and Newtownabbey": { name: "NI Water", id: "ni-water" },
  "Ards and North Down": { name: "NI Water", id: "ni-water" },
  "Armagh City, Banbridge and Craigavon": { name: "NI Water", id: "ni-water" },
  Belfast: { name: "NI Water", id: "ni-water" },
  "Causeway Coast and Glens": { name: "NI Water", id: "ni-water" },
  "Derry City and Strabane": { name: "NI Water", id: "ni-water" },
  "Fermanagh and Omagh": { name: "NI Water", id: "ni-water" },
  "Lisburn and Castlereagh": { name: "NI Water", id: "ni-water" },
  "Mid and East Antrim": { name: "NI Water", id: "ni-water" },
  "Mid Ulster": { name: "NI Water", id: "ni-water" },
  "Newry, Mourne and Down": { name: "NI Water", id: "ni-water" },
};

const UNKNOWN_SUPPLIER: SupplierInfo = { name: "Unknown", id: "unknown" };

export function getSupplier(city: string): SupplierInfo {
  return SUPPLIER_MAP[city] ?? UNKNOWN_SUPPLIER;
}
