/**
 * Build the complete Scottish Water zone-to-postcode mapping.
 *
 * Takes the zone-discovery.json (postcode→zone from web scraping)
 * and fills in gaps by assigning unmatched postcodes to the nearest
 * known zone in the same prefix area.
 *
 * Outputs: src/lib/scottish-zones.ts
 */

import { readFileSync, writeFileSync } from "fs";

interface Discovery {
  [district: string]: string | null;
}

function main() {
  const discovery: Discovery = JSON.parse(
    readFileSync("data/scottish-water/zone-discovery.json", "utf-8"),
  );

  // Build zone → postcodes from known mappings
  const zoneToPostcodes: Record<string, string[]> = {};
  const districtToZone: Record<string, string> = {};

  for (const [district, zone] of Object.entries(discovery)) {
    if (zone) {
      districtToZone[district] = zone;
      if (!zoneToPostcodes[zone]) zoneToPostcodes[zone] = [];
      zoneToPostcodes[zone].push(district);
    }
  }

  // For unfound districts, find the nearest known district in the same prefix
  const getPrefix = (d: string) => d.replace(/\d+$/, "");
  const getNumber = (d: string) => parseInt(d.replace(/^[A-Z]+/, ""), 10);

  // Group found districts by prefix
  const foundByPrefix: Record<string, { district: string; num: number; zone: string }[]> = {};
  for (const [district, zone] of Object.entries(districtToZone)) {
    const prefix = getPrefix(district);
    if (!foundByPrefix[prefix]) foundByPrefix[prefix] = [];
    foundByPrefix[prefix].push({
      district,
      num: getNumber(district),
      zone,
    });
  }

  // Sort each prefix group by number
  for (const arr of Object.values(foundByPrefix)) {
    arr.sort((a, b) => a.num - b.num);
  }

  // Assign unfound districts
  let assigned = 0;
  for (const [district, zone] of Object.entries(discovery)) {
    if (zone) continue; // Already found

    const prefix = getPrefix(district);
    const num = getNumber(district);
    const candidates = foundByPrefix[prefix];

    if (!candidates || candidates.length === 0) {
      // No found districts in this prefix at all — find nearest prefix
      // For now, skip and handle manually
      continue;
    }

    // Find nearest by number
    let nearest = candidates[0];
    let minDist = Math.abs(num - nearest.num);
    for (const c of candidates) {
      const d = Math.abs(num - c.num);
      if (d < minDist) {
        minDist = d;
        nearest = c;
      }
    }

    districtToZone[district] = nearest.zone;
    if (!zoneToPostcodes[nearest.zone]) zoneToPostcodes[nearest.zone] = [];
    zoneToPostcodes[nearest.zone].push(district);
    assigned++;
  }

  // Handle truly orphaned prefixes (no found districts at all)
  // These are HS (Western Isles), ZE (Shetland), some others
  // Assign them to geographically close zones
  const FALLBACK_ZONES: Record<string, string> = {
    HS: "Barra Western Isles", // Western Isles - use any Western Isles zone
    ZE: "Yell Shetland",      // Shetland
  };

  for (const [district, zone] of Object.entries(discovery)) {
    if (zone || districtToZone[district]) continue;
    const prefix = getPrefix(district);
    const fallback = FALLBACK_ZONES[prefix];
    if (fallback) {
      districtToZone[district] = fallback;
      if (!zoneToPostcodes[fallback]) zoneToPostcodes[fallback] = [];
      zoneToPostcodes[fallback].push(district);
      assigned++;
    }
  }

  // Check what's still unassigned
  const unassigned = Object.entries(discovery)
    .filter(([d, z]) => !z && !districtToZone[d])
    .map(([d]) => d);

  console.log(`Direct from scraping: ${Object.values(discovery).filter(Boolean).length}`);
  console.log(`Assigned by proximity: ${assigned}`);
  console.log(`Still unassigned: ${unassigned.length}`);
  if (unassigned.length > 0) {
    console.log(`  ${unassigned.join(", ")}`);
  }

  // Sort postcodes within each zone
  for (const zone of Object.keys(zoneToPostcodes)) {
    zoneToPostcodes[zone].sort();
  }

  // Build zone slug mapping
  const zoneSlugMap: Record<string, string> = {};
  for (const zone of Object.keys(zoneToPostcodes)) {
    zoneSlugMap[zone] = zone.toLowerCase().replace(/\s+/g, "-");
  }

  // Write the TypeScript mapping file
  const tsContent = `/**
 * Scottish Water zone-to-postcode mapping.
 *
 * Scottish Water divides its supply area into ~277 regulatory zones.
 * This mapping assigns each of Scotland's ${Object.keys(districtToZone).length} postcode districts to a zone.
 *
 * Generated by scripts/build-scottish-zones-mapping.ts from zone-discovery.json.
 */

/** Maps zone name → array of postcode districts served by that zone */
export const SCOTTISH_ZONE_POSTCODES: Record<string, string[]> = ${JSON.stringify(zoneToPostcodes, null, 2)};

/** Maps zone name → URL slug (for PDF downloads) */
export const SCOTTISH_ZONE_SLUGS: Record<string, string> = ${JSON.stringify(zoneSlugMap, null, 2)};

/**
 * Look up which Scottish Water zone a postcode district belongs to.
 * Returns null if the postcode is not in Scotland.
 */
export function getScottishZone(district: string): string | null {
  for (const [zone, postcodes] of Object.entries(SCOTTISH_ZONE_POSTCODES)) {
    if (postcodes.includes(district)) return zone;
  }
  return null;
}

/**
 * Check if a postcode district is served by Scottish Water.
 */
export function isScottishPostcode(district: string): boolean {
  return getScottishZone(district) !== null;
}
`;

  writeFileSync("src/lib/scottish-zones.ts", tsContent);
  console.log(`\nWritten src/lib/scottish-zones.ts`);
  console.log(`  ${Object.keys(zoneToPostcodes).length} zones → ${Object.keys(districtToZone).length} postcodes`);

  // Save the zone-postcodes.json for reference
  writeFileSync(
    "data/scottish-water/zone-postcodes.json",
    JSON.stringify(zoneToPostcodes, null, 2),
  );
}

main();
